#
# 禁止在项目中build
#
SET(CMAKE_DISABLE_SOURCE_CHANGES ON)
SET(CMAKE_DISABLE_IN_SOURCE_BUILD ON)


#
# 添加rpath
#
SET(CMAKE_SKIP_BUILD_RPATH FALSE)
SET(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
SET(CMAKE_INSTALL_RPATH ${CMAKE_INSTALL_PREFIX})
SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)


#
# 设置工程组
#
SET_PROPERTY(GLOBAL PROPERTY USE_FOLDERS ON)