#
# 检测平台
#
IF(CMAKE_SIZEOF_VOID_P MATCHES 8)

	MESSAGE(STATUS "Detected ${CMAKE_SYSTEM} ${CMAKE_SYSTEM_PROCESSOR} 64-bit Platform")

ELSE()

	MESSAGE(STATUS "Detected ${CMAKE_SYSTEM} ${CMAKE_SYSTEM_PROCESSOR} 32-bit Platform")

ENDIF()
